### ISSUE TITLE
HUDI Feature Group creation List Index out of range

### ISSUE THREAD

**Issue by moritzmeister** [logicalclocks/feature-store-api#202]
When creating a hudi feature group I run into a list index out of range for the primary key.

The primary key of the feature group is set correctly before the rest call to create the feature group is made. It seems the backend does not return the information of primary keys after creation in the DTO it sends back.

To reproduce in demo project:
```python
import hsfs
conn = hsfs.connection()
fs = conn.get_feature_store()

fg = fs.create_feature_group("games_features", version=2, statistics_config=False, primary_key=["home_team_id"], partition_key=["home_team_id", "away_team_id"])

fg.save(fs.get_feature_group("games_features").read())
```

Throws:
```
An error was encountered:
list index out of range
Traceback (most recent call last):
  File "/srv/hops/anaconda/envs/theenv/lib/python3.7/site-packages/hsfs/feature_group.py", line 262, in save
    self._feature_group_engine.save(self, feature_dataframe, write_options)
  File "/srv/hops/anaconda/envs/theenv/lib/python3.7/site-packages/hsfs/core/feature_group_engine.py", line 69, in save
    online_write_options,
  File "/srv/hops/anaconda/envs/theenv/lib/python3.7/site-packages/hsfs/engine/spark.py", line 164, in save_dataframe
    offline_write_options,
  File "/srv/hops/anaconda/envs/theenv/lib/python3.7/site-packages/hsfs/engine/spark.py", line 196, in _save_offline_dataframe
    self._spark_context,
  File "/srv/hops/anaconda/envs/theenv/lib/python3.7/site-packages/hsfs/core/hudi_engine.py", line 76, in __init__
    self._pre_combine_key = feature_group.primary_key[0]
IndexError: list index out of range
```

**Comment by moritzmeister** [comment]
closed by HOPSWORSK-2238
